import React, { useEffect, useState } from 'react'
import { api } from '../api.js'

export default function ContractArchiveTable({ contract, user, canManage, onChanged }) {
  const [rows,setRows]=useState([]), [file,setFile]=useState(null), [note,setNote]=useState(''), [error,setError]=useState(''), [busy,setBusy]=useState(false), [preview,setPreview]=useState(null), [deleteTarget,setDeleteTarget]=useState(null), [confirmation,setConfirmation]=useState('')
  const canDelete = user?.role?.name === 'Admin'
  async function load(){ if(!contract?.id)return; try{setRows(await api(`/crm/contracts/${contract.id}/archives`));setError('')}catch(e){setError(e.message)} }
  useEffect(()=>{load()},[contract?.id])
  useEffect(()=>()=>{if(preview?.url)URL.revokeObjectURL(preview.url)},[preview])
  async function blob(row,mode){const r=await api(`/crm/contract-archives/${row.id}/${mode}`);return r.blob()}
  async function upload(e){e.preventDefault();if(!file)return;setBusy(true);setError('');try{const fd=new FormData();fd.append('archive_file',file);if(note.trim())fd.append('note',note.trim());await api(`/crm/contracts/${contract.id}/archives`,{method:'POST',body:fd});setFile(null);setNote('');e.target.reset();await load();onChanged?.()}catch(err){setError(err.message)}finally{setBusy(false)}}
  async function openPreview(row){try{const b=await blob(row,'preview');setPreview({row,url:URL.createObjectURL(b)})}catch(e){setError(e.message)}}
  async function download(row){try{const b=await blob(row,'download');const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download=row.original_filename||`${row.archive_number}.pdf`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}catch(e){setError(e.message)}}
  async function print(row){try{const b=await blob(row,'preview');const u=URL.createObjectURL(b);const w=window.open(u,'_blank');if(!w){setError('A böngésző blokkolta a nyomtatási ablakot. Engedélyezd a felugró ablakokat.');URL.revokeObjectURL(u);return}setTimeout(()=>{try{w.print()}catch{}},900);setTimeout(()=>URL.revokeObjectURL(u),60000)}catch(e){setError(e.message)}}
  async function remove(e){e.preventDefault();if(!deleteTarget||confirmation!=='TÖRÖL')return;setBusy(true);try{await api(`/crm/contract-archives/${deleteTarget.id}`,{method:'DELETE',body:{confirmation}});setDeleteTarget(null);setConfirmation('');await load();onChanged?.()}catch(err){setError(err.message)}finally{setBusy(false)}}
  return <div className="contract-archive-section">
    <h3>Papíralapú szerződés PDF archívuma</h3>
    {error&&<div className="error">{error}</div>}
    {canManage&&<form className="contract-archive-upload" onSubmit={upload}><label>PDF<input type="file" accept="application/pdf,.pdf" required onChange={e=>setFile(e.target.files?.[0]||null)}/></label><label>Megjegyzés<input value={note} onChange={e=>setNote(e.target.value)} maxLength="500"/></label><button disabled={busy||!file}>{busy?'Feltöltés...':'PDF archiválása'}</button></form>}
    <div className="table-wrap"><table><thead><tr><th>Archív azonosító</th><th>Fájl</th><th>Megjegyzés</th><th>Feltöltve</th><th></th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><strong>{row.archive_number}</strong></td><td>{row.original_filename}</td><td>{row.note||''}</td><td>{new Date(row.created_at).toLocaleString('hu-HU')}<small>{row.uploaded_by_name||'Rendszer'}</small></td><td><div className="archive-row-actions"><button className="secondary small-button" onClick={()=>openPreview(row)}>Előnézet</button><button className="secondary small-button" onClick={()=>print(row)}>Nyomtatás</button><button className="secondary small-button" onClick={()=>download(row)}>Letöltés</button>{canDelete&&<button className="danger small-button" onClick={()=>{setDeleteTarget(row);setConfirmation('')}}>Törlés</button>}</div></td></tr>)}{!rows.length&&<tr><td colSpan="5" className="muted">Ehhez a szerződéshez még nincs archivált PDF.</td></tr>}</tbody></table></div>
    {preview&&<div className="modal-backdrop archive-preview-backdrop no-print" onMouseDown={e=>{if(e.target===e.currentTarget)setPreview(null)}}><section className="modal-card archive-preview-modal"><div className="modal-head"><div><h2>{preview.row.archive_number}</h2><p>{preview.row.original_filename}</p></div><button className="secondary" onClick={()=>setPreview(null)}>Bezárás</button></div><div className="archive-preview-surface"><iframe src={preview.url} title="Szerződés PDF előnézet"/></div><div className="inline-actions modal-actions"><button className="secondary" onClick={()=>print(preview.row)}>Nyomtatás</button><button className="secondary" onClick={()=>download(preview.row)}>Letöltés</button></div></section></div>}
    {deleteTarget&&<div className="modal-backdrop no-print"><section className="modal-card archive-delete-modal"><div className="modal-head"><div><h2>Szerződés PDF törlése</h2><p>{deleteTarget.archive_number} · {deleteTarget.original_filename}</p></div><button className="secondary" onClick={()=>setDeleteTarget(null)}>Bezárás</button></div><div className="warning-box"><strong>Végleges törlés.</strong><p>Csak Admin hajthatja végre; az auditnapló megmarad.</p></div><form onSubmit={remove}><label>A megerősítéshez írd be: <strong>TÖRÖL</strong><input autoFocus value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label><div className="modal-actions inline-actions"><button type="button" className="secondary" onClick={()=>setDeleteTarget(null)}>Mégse</button><button className="danger" disabled={confirmation!=='TÖRÖL'||busy}>Végleges törlés</button></div></form></section></div>}
  </div>
}
