from __future__ import annotations

import re
from typing import Any

IMPORT_INTERNAL_ID_RE = re.compile(r"^IMP-\d{8}-\d+$", re.IGNORECASE)


def is_hidden_internal_id(value: str | None) -> bool:
    """Return True for technical identifiers generated by the Excel importer."""
    return bool(value and IMPORT_INTERNAL_ID_RE.fullmatch(value.strip()))


def visible_internal_id(value: str | None) -> str | None:
    """Return a user-facing internal identifier, hiding importer-only keys."""
    if not value or is_hidden_internal_id(value):
        return None
    return value


def asset_display_name(asset: Any) -> str:
    """Build a useful user-facing label without exposing technical import keys."""
    type_name = getattr(asset, "model", None) or getattr(asset, "type", None)
    manufacturer = getattr(asset, "manufacturer", None)
    serial_number = getattr(asset, "serial_number", None)
    public_id = visible_internal_id(getattr(asset, "internal_id", None))

    product = " / ".join(part for part in [manufacturer, type_name] if part)
    if serial_number and product:
        return f"{product} · gyári szám: {serial_number}"
    if serial_number:
        return f"Gyári szám: {serial_number}"
    if product:
        return product
    if public_id:
        return public_id
    return "Eszköz"
