import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { hasModule, hasPermission, moduleLabel } from '../src/utils/permissions.js'

test('modul- és funkciójogosultság segédfüggvények', () => {
  const user = { role: { name: 'Irodai felhasználó' }, modules: ['service', 'hr'], permissions: ['service.access', 'hr.access', 'hr.summary.view'] }
  assert.equal(hasModule(user, 'service'), true)
  assert.equal(hasModule(user, 'crm'), false)
  assert.equal(hasPermission(user, 'hr.summary.view'), true)
  assert.equal(hasPermission(user, 'crm.write'), false)
  assert.equal(moduleLabel('service'), 'Szerviz')
})

test('admin rendszerszinten teljes funkciójogosultságot kap', () => {
  const admin = { role: { name: 'Admin' }, modules: ['service', 'hr', 'crm', 'admin'], permissions: [] }
  assert.equal(hasPermission(admin, 'hr.admin'), true)
  assert.equal(hasPermission(admin, 'crm.admin'), true)
})

test('bejelentkezés után modulválasztóra navigál és a modulútvonalakat védi', () => {
  const source = readFileSync(new URL('../src/App.jsx', import.meta.url), 'utf8')
  assert.match(source, /navigate\('\/modules', \{ replace: true \}\)/)
  assert.match(source, /if \(currentModule && !hasModule\(user, currentModule\)\) return <Navigate to="\/modules" replace \/>/)
  assert.match(source, /<Route path="\/service\/work-orders"/)
  assert.match(source, /<Route path="\/hr"/)
  assert.match(source, /<Route path="\/crm"/)
  assert.match(source, /<Route path="\/admin\/users"/)
})

test('felhasználókezelőben a modul- és funkciójogosultságok szerkeszthetők', () => {
  const source = readFileSync(new URL('../src/pages/Users.jsx', import.meta.url), 'utf8')
  assert.match(source, /api\('\/users\/permissions'\)/)
  assert.match(source, /permission_codes/)
  assert.match(source, /Modulok és jogosultságok/)
  assert.match(source, /if \(!permission\.is_module_access && moduleAccess\) selected\.add\(moduleAccess\)/)
})

test('admin auditnapló strukturált és hash-chain integritási nézettel elérhető', () => {
  const appSource = readFileSync(new URL('../src/App.jsx', import.meta.url), 'utf8')
  const layoutSource = readFileSync(new URL('../src/components/Layout.jsx', import.meta.url), 'utf8')
  const auditSource = readFileSync(new URL('../src/pages/AuditLogs.jsx', import.meta.url), 'utf8')
  assert.match(appSource, /<Route path="\/admin\/audit" element={<AdminRoleRoute user={user}><AuditLogs \/><\/AdminRoleRoute>} \/>/)
  assert.match(layoutSource, /\['\/admin\/audit', 'Auditnapló'\]/)
  assert.match(auditSource, /api\('\/audit-logs\/integrity'\)/)
  assert.match(auditSource, /row\.changes/)
  assert.match(auditSource, /row\.request_id/)
  assert.match(auditSource, /row\.entry_hash/)
})

test('integrált biztonsági mentés külön admin jogosultsággal és oldallal rendelkezik', () => {
  const appSource = readFileSync(new URL('../src/App.jsx', import.meta.url), 'utf8')
  const layoutSource = readFileSync(new URL('../src/components/Layout.jsx', import.meta.url), 'utf8')
  const usersSource = readFileSync(new URL('../src/pages/Users.jsx', import.meta.url), 'utf8')
  const backupSource = readFileSync(new URL('../src/pages/Backups.jsx', import.meta.url), 'utf8')
  assert.match(appSource, /path="\/admin\/backups"/)
  assert.match(appSource, /admin\.backup\.manage/)
  assert.match(layoutSource, /\['\/admin\/backups', 'Biztonsági mentések', 'admin\.backup\.manage'\]/)
  assert.match(usersSource, /admin\.backup\.restore/)
  assert.match(usersSource, /admin\.backup\.manage/)
  assert.match(backupSource, /\/backups\/schedule/)
  assert.match(backupSource, /\/backups\/master/)
  assert.match(backupSource, /MASTER mentés készítése most/)
  assert.match(backupSource, /admin\.backup\.restore/)
  assert.match(backupSource, /VISSZAALLIT/)
  assert.match(backupSource, /\/backups\/restores/)
  assert.match(backupSource, /pre-restore MASTER/)
  assert.match(backupSource, /post-restore MASTER/)
  assert.match(backupSource, /HELYREALLITAS_KESZ/)
  assert.match(backupSource, /rollback_restore_backup_id/)
  assert.match(backupSource, /deployment_fingerprint/)
  assert.match(backupSource, /restoreRequestedRef/)
})

test('HR modul saját szabadság, jóváhagyás, összesítés és admin útvonalakkal rendelkezik', () => {
  const appSource = readFileSync(new URL('../src/App.jsx', import.meta.url), 'utf8')
  const layoutSource = readFileSync(new URL('../src/components/Layout.jsx', import.meta.url), 'utf8')
  const leaveSource = readFileSync(new URL('../src/pages/HrLeave.jsx', import.meta.url), 'utf8')
  const approvalSource = readFileSync(new URL('../src/pages/HrApprovals.jsx', import.meta.url), 'utf8')
  const adminSource = readFileSync(new URL('../src/pages/HrAdmin.jsx', import.meta.url), 'utf8')
  assert.match(appSource, /path="\/hr\/leave"/)
  assert.match(appSource, /permission="hr\.leave\.self"/)
  assert.match(appSource, /path="\/hr\/approvals"/)
  assert.match(appSource, /permission="hr\.leave\.approve"/)
  assert.match(appSource, /path="\/hr\/summary"/)
  assert.match(appSource, /permission="hr\.summary\.view"/)
  assert.match(appSource, /path="\/hr\/admin"/)
  assert.match(layoutSource, /hr\.leave\.approve/)
  assert.match(leaveSource, /api\(`\/hr\/me\?year=\$\{year\}`\)/)
  assert.match(leaveSource, /\/hr\/me\/leave-requests/)
  assert.match(approvalSource, /\/hr\/approvals\/\$\{row\.id\}\/\$\{decision\}/)
  assert.match(adminSource, /\/hr\/admin\/employees/)
  assert.match(adminSource, /\/hr\/admin\/calendar/)
})

test('szabadságigény jogosultság kiválasztása saját szabadságjogot is bekapcsol', () => {
  const usersSource = readFileSync(new URL('../src/pages/Users.jsx', import.meta.url), 'utf8')
  assert.match(usersSource, /permission\.code === 'hr\.leave\.request'\) selected\.add\('hr\.leave\.self'\)/)
  assert.match(usersSource, /permission\.code === 'hr\.leave\.self'\) selected\.delete\('hr\.leave\.request'\)/)
})

test('CRM alap ügyfélnézettel, lehetőségekkel és aktivitásokkal rendelkezik', () => {
  const appSource = readFileSync(new URL('../src/App.jsx', import.meta.url), 'utf8')
  const layoutSource = readFileSync(new URL('../src/components/Layout.jsx', import.meta.url), 'utf8')
  const customerSource = readFileSync(new URL('../src/pages/CrmCustomerDetail.jsx', import.meta.url), 'utf8')
  const opportunitySource = readFileSync(new URL('../src/pages/CrmOpportunities.jsx', import.meta.url), 'utf8')
  const activitySource = readFileSync(new URL('../src/pages/CrmActivities.jsx', import.meta.url), 'utf8')
  assert.match(appSource, /path="\/crm\/customers"/)
  assert.match(appSource, /path="\/crm\/customers\/:customerId"/)
  assert.match(appSource, /path="\/crm\/opportunities"/)
  assert.match(appSource, /path="\/crm\/activities"/)
  assert.match(layoutSource, /\['\/crm\/customers', 'Ügyfelek'\]/)
  assert.match(customerSource, /\/crm\/customers\/\$\{customerId\}/)
  assert.match(opportunitySource, /api\('\/crm\/opportunities'/)
  assert.match(activitySource, /api\(form\.id \? `\/crm\/activities\/\$\{form\.id\}` : '\/crm\/activities'/)
  assert.match(activitySource, /`\/crm\/activities\/\$\{row\.id\}\/opportunity`/)
  assert.match(activitySource, /Lehetőség létrehozása/)
})

test('CRM szerződéskezelés telephely- és eszközhatállyal és munkalap-integrációval rendelkezik', () => {
  const appSource = readFileSync(new URL('../src/App.jsx', import.meta.url), 'utf8')
  const layoutSource = readFileSync(new URL('../src/components/Layout.jsx', import.meta.url), 'utf8')
  const contractSource = readFileSync(new URL('../src/pages/CrmContracts.jsx', import.meta.url), 'utf8')
  const workOrderSource = readFileSync(new URL('../src/pages/WorkOrders.jsx', import.meta.url), 'utf8')
  const customerSource = readFileSync(new URL('../src/pages/CrmCustomerDetail.jsx', import.meta.url), 'utf8')
  assert.match(appSource, /path="\/crm\/contracts"/)
  assert.match(layoutSource, /\['\/crm\/contracts', 'Szerződések'\]/)
  assert.match(contractSource, /crm\.contract\.manage/)
  assert.match(contractSource, /location_ids/)
  assert.match(contractSource, /asset_ids/)
  assert.match(workOrderSource, /\/work-orders\/contract-options/)
  assert.match(workOrderSource, /contract_id/)
  assert.match(customerSource, /data\.contracts/)
})

test('6. fázis központi értesítésekkel, modulriportokkal és CSV exporttal rendelkezik', () => {
  const appSource = readFileSync(new URL('../src/App.jsx', import.meta.url), 'utf8')
  const layoutSource = readFileSync(new URL('../src/components/Layout.jsx', import.meta.url), 'utf8')
  const notificationsSource = readFileSync(new URL('../src/pages/Notifications.jsx', import.meta.url), 'utf8')
  const serviceReport = readFileSync(new URL('../src/pages/ServiceReports.jsx', import.meta.url), 'utf8')
  const hrReport = readFileSync(new URL('../src/pages/HrReports.jsx', import.meta.url), 'utf8')
  const crmReport = readFileSync(new URL('../src/pages/CrmReports.jsx', import.meta.url), 'utf8')
  assert.match(appSource, /path="\/notifications"/)
  assert.match(appSource, /path="\/service\/reports"/)
  assert.match(appSource, /path="\/hr\/reports"/)
  assert.match(appSource, /path="\/crm\/reports"/)
  assert.match(layoutSource, /\/notifications\/unread-count/)
  assert.match(notificationsSource, /\/notifications\/read-all/)
  assert.match(serviceReport, /\/reports\/service\.csv/)
  assert.match(hrReport, /\/reports\/hr\.csv/)
  assert.match(crmReport, /\/reports\/crm\.csv/)
})

test('2026 RLB szabadságimport külön kezeli az éves és betegszabadság adatokat', () => {
  const leaveSource = readFileSync(new URL('../src/pages/HrLeave.jsx', import.meta.url), 'utf8')
  const adminSource = readFileSync(new URL('../src/pages/HrAdmin.jsx', import.meta.url), 'utf8')
  assert.match(leaveSource, /sick_leave_used_days/)
  assert.match(leaveSource, /RLB 2026 nyilvántartás/)
  assert.match(adminSource, /\/hr\/admin\/imported-leave/)
  assert.match(adminSource, /Gyermekek után járó/)
  assert.match(adminSource, /Betegszabadság keret/)
})

test('szerződés Excel-mezők, PDF archívum és HR heti-havi-éves naptár elérhető', () => {
  const contractSource = readFileSync(new URL('../src/pages/CrmContracts.jsx', import.meta.url), 'utf8')
  const archiveSource = readFileSync(new URL('../src/components/ContractArchiveTable.jsx', import.meta.url), 'utf8')
  const hrSource = readFileSync(new URL('../src/pages/HrSummary.jsx', import.meta.url), 'utf8')
  assert.match(contractSource, /companyCodes=\['DRH','SP','GXR'\]/)
  assert.match(contractSource, /Szerződés tárgya/)
  assert.match(contractSource, /Számlázási időszak \/ gyakoriság/)
  assert.match(contractSource, /Karbantartási ciklus/)
  assert.match(contractSource, /Szerviz\/eszköz sor/)
  assert.match(archiveSource, /application\/pdf/)
  assert.match(archiveSource, /Nyomtatás/)
  assert.match(archiveSource, /TÖRÖL/)
  assert.match(hrSource, /Heti/)
  assert.match(hrSource, /Havi/)
  assert.match(hrSource, /Éves/)
  assert.match(hrSource, /\/hr\/summary\/calendar/)
})

test('az admin minden ügyfél-, helyszín- és kapcsolattartó-adatot kezelhet', () => {
  const source = readFileSync(new URL('../src/pages/Customers.jsx', import.meta.url), 'utf8')
  assert.match(source, /const isAdmin = user\?\.role\?\.name === 'Admin'/)
  assert.match(source, /api\(`\/locations\/\$\{editingLocationId\}`.*method: 'PUT'/s)
  assert.match(source, /api\(`\/customers\/\$\{customerId\}\/contacts\/\$\{editingContactId\}`.*method: 'PUT'/s)
  assert.match(source, /<LocationList customer=\{row\} canManage=\{isAdmin\}/)
  assert.match(source, /<ContactList customer=\{row\} canManage=\{isAdmin\}/)
  assert.match(source, /isAdmin && <button className="danger" onClick=\{\(\) => removeCustomer\(row\)\}>Törlés<\/button>/)
})

test('a dashboard felül mutatja a naptárat és benne a jóváhagyott technikusi távollétet', () => {
  const source = readFileSync(new URL('../src/pages/Dashboard.jsx', import.meta.url), 'utf8')
  const css = readFileSync(new URL('../src/styles/app.css', import.meta.url), 'utf8')
  assert.ok(source.indexOf('className="panel calendar-panel"') < source.indexOf('className="panel maintenance-planning-panel"'))
  assert.match(source, /calendar\?\.leave_events \|\| \[\]/)
  assert.match(source, /calendar-leave-grid/)
  assert.match(source, /Jóváhagyott távollét/)
  assert.match(css, /\.calendar-leave-event/)
})

test('az inaktív helyszín megmarad az előzményekben, de új kiválasztásból eltűnik', () => {
  const customersSource = readFileSync(new URL('../src/pages/Customers.jsx', import.meta.url), 'utf8')
  const assetFormSource = readFileSync(new URL('../src/pages/AssetForm.jsx', import.meta.url), 'utf8')
  const workOrderSource = readFileSync(new URL('../src/pages/WorkOrders.jsx', import.meta.url), 'utf8')
  const contractSource = readFileSync(new URL('../src/pages/CrmContracts.jsx', import.meta.url), 'utf8')
  const crmCustomerSource = readFileSync(new URL('../src/pages/CrmCustomerDetail.jsx', import.meta.url), 'utf8')

  assert.match(customersSource, /body: \{ is_active: nextActive \}/)
  assert.match(customersSource, /inaktiválás/)
  assert.match(assetFormSource, /location\.is_active !== false \|\| \(editing/)
  assert.match(workOrderSource, /location\.is_active !== false \|\| \(editing/)
  assert.match(contractSource, /selectableLocations=locations\.filter/)
  assert.match(crmCustomerSource, /selectableLocations = locations\.filter/)
  assert.match(crmCustomerSource, /inaktív \(meglévő\)/)
})

test('a jóváhagyott saját szabadság visszavonása külön vezetői döntést kér', () => {
  const leaveSource = readFileSync(new URL('../src/pages/HrLeave.jsx', import.meta.url), 'utf8')
  const approvalSource = readFileSync(new URL('../src/pages/HrApprovals.jsx', import.meta.url), 'utf8')

  assert.match(leaveSource, /request-cancellation/)
  assert.match(leaveSource, /Visszavonás jóváhagyásra vár/)
  assert.match(leaveSource, /a jóváhagyó döntéséig érvényben marad/)
  assert.match(approvalSource, /row\.approval_kind === 'cancellation'/)
  assert.match(approvalSource, /cancellation\/\$\{decision\}/)
  assert.match(approvalSource, /Visszavonás engedélyezése/)
  assert.match(approvalSource, /Visszavonás elutasítása/)
})

test('Beszerzés modul minden user számára külön modulként és külön jóváhagyási joggal van bekötve', () => {
  const appSource = readFileSync(new URL('../src/App.jsx', import.meta.url), 'utf8')
  const layoutSource = readFileSync(new URL('../src/components/Layout.jsx', import.meta.url), 'utf8')
  const selectorSource = readFileSync(new URL('../src/pages/ModuleSelector.jsx', import.meta.url), 'utf8')
  const userSource = readFileSync(new URL('../src/pages/Users.jsx', import.meta.url), 'utf8')
  const requestSource = readFileSync(new URL('../src/pages/ProcurementNew.jsx', import.meta.url), 'utf8')
  const approvalSource = readFileSync(new URL('../src/pages/ProcurementApprovals.jsx', import.meta.url), 'utf8')
  const detailSource = readFileSync(new URL('../src/pages/ProcurementDetail.jsx', import.meta.url), 'utf8')

  assert.match(appSource, /path="\/procurement"/)
  assert.match(appSource, /path="\/procurement\/new"/)
  assert.match(appSource, /path="\/procurement\/approvals"/)
  assert.match(appSource, /permission="procurement\.approve"/)
  assert.match(layoutSource, /\['\/procurement\/approvals', 'Jóváhagyások', 'procurement\.approve'\]/)
  assert.match(selectorSource, /code: 'procurement'/)
  assert.match(userSource, /'procurement'/)
  assert.match(requestSource, /Beszerzés célja/)
  assert.match(requestSource, /Összérték/)
  assert.match(requestSource, /multiple/)
  assert.match(approvalSource, /requester\.full_name/)
  assert.match(approvalSource, /total_amount/)
  assert.match(detailSource, /procurement\.approve/)
  assert.match(detailSource, /Elutasításkor a jóváhagyói megjegyzés kötelező/)
})

test('v0.29 admin felületről ellenőrizhető és tesztelhető a mobil push regisztráció', () => {
  const userSource = readFileSync(new URL('../src/pages/Users.jsx', import.meta.url), 'utf8')
  assert.match(userSource, /Mobil eszközök/)
  assert.match(userSource, /\/mobile-devices/)
  assert.match(userSource, /\/test-push/)
  assert.match(userSource, /Teszt push/)
  assert.match(userSource, /push_enabled/)
  assert.doesNotMatch(userSource, /device\.push_token(?!_)/)
})

test('v0.30 érzékeny műveletek MFA step-up modalt és egyszeri retry-t használnak', () => {
  const modalSource = readFileSync(new URL('../src/components/SecurityStepUpModal.jsx', import.meta.url), 'utf8')
  const backupSource = readFileSync(new URL('../src/pages/Backups.jsx', import.meta.url), 'utf8')
  const settingsSource = readFileSync(new URL('../src/pages/Settings.jsx', import.meta.url), 'utf8')
  const usersSource = readFileSync(new URL('../src/pages/Users.jsx', import.meta.url), 'utf8')

  assert.match(modalSource, /\/auth\/mfa\/step-up/)
  assert.match(modalSource, /pending\.resolve\(await pending\.action\(\)\)/)
  assert.match(modalSource, /a second recent_mfa_required response is returned/i)
  assert.match(backupSource, /runSensitive\(\(\) => api\(`\/backups/)
  assert.match(backupSource, /runSensitive\(\(\) => api\('\/backups\/recovery\/clear'/)
  assert.match(settingsSource, /runSensitive\(\(\) => api\('\/settings\/restore'/)
  assert.match(usersSource, /runSensitive\(\(\) => api\('\/users'/)
})
