import React, { useEffect, useMemo, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { api, downloadFile } from '../api.js'
import { Field } from '../components/FormField.jsx'
import ContractArchiveTable from '../components/ContractArchiveTable.jsx'
import { hasPermission } from '../utils/permissions.js'

const statuses=['tervezet','aktív','lejárt','felmondott','lezárt']
const companyCodes=['DRH','SP','GXR']
const emptyLine=()=>({rental_fee:'',operating_fee:'',click_fee:'',included_quantity:'',operator_company:'',operator_site:'',maintenance_cycle:'',device_group:'',device_name:'',serial_number:'',parts_terms:'',toner_terms:'',travel_labor_terms:'',repair_terms:'',sla:'',replacement_device:''})
const blank={id:null,version:null,customer_id:'',company_code:'DRH',contracting_party_name:'',contracting_party_address:'',contract_number:'',contract_type:'',subject:'',start_date:'',end_date:'',term_text:'',status:'aktív',billing_frequency:'',payment_terms:'',billing_name:'',service_confirmation:'',e_invoice_email:'',price_adjustment_terms:'',sla:'',billing_model:'',note:'',location_ids:[],asset_ids:[],service_lines:[emptyLine()]}
const fmt=v=>v?new Intl.DateTimeFormat('hu-HU').format(new Date(`${v}T00:00:00`)):''
const clean=v=>String(v??'').trim()||null

export default function CrmContracts({user}){
  const [sp,setSp]=useSearchParams(),[contracts,setContracts]=useState([]),[customers,setCustomers]=useState([]),[customerDetail,setCustomerDetail]=useState(null),[form,setForm]=useState(null),[expanded,setExpanded]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(false)
  const canManage=hasPermission(user,'crm.contract.manage')
  const filterCustomer=sp.get('customer')||'',filterStatus=sp.get('status')||'',filterCompany=sp.get('company')||'',q=sp.get('q')||''
  async function load(){setLoading(true);try{const p=new URLSearchParams();if(filterCustomer)p.set('customer_id',filterCustomer);if(filterStatus)p.set('status',filterStatus);if(filterCompany)p.set('company_code',filterCompany);if(q)p.set('q',q);const [rows,cs]=await Promise.all([api(`/crm/contracts?${p}`),api('/crm/customers')]);setContracts(rows);setCustomers(cs);setError('')}catch(e){setError(e.message)}finally{setLoading(false)}}
  useEffect(()=>{load()},[filterCustomer,filterStatus,filterCompany,q])
  useEffect(()=>{const id=form?.customer_id?Number(form.customer_id):null;if(!id){setCustomerDetail(null);return}let active=true;api(`/crm/customers/${id}`).then(d=>{if(active)setCustomerDetail(d)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[form?.customer_id])
  const locations=customerDetail?.customer?.locations||[],assets=customerDetail?.assets||[]
  const selectableLocations=locations.filter(r=>r.is_active!==false||(form?.id&&form.location_ids.map(Number).includes(r.id)))
  const customerName=useMemo(()=>customers.find(r=>r.id===Number(form?.customer_id))?.name||'',[customers,form?.customer_id])
  function filter(k,v){setSp(prev=>{const n=new URLSearchParams(prev);v?n.set(k,v):n.delete(k);return n},{replace:true})}
  function startNew(){setForm({...blank,customer_id:filterCustomer||'',company_code:filterCompany||'DRH',service_lines:[emptyLine()]});setCustomerDetail(null)}
  function startEdit(r){setForm({...blank,...r,customer_id:String(r.customer_id),start_date:r.start_date||'',end_date:r.end_date||'',location_ids:r.location_ids||[],asset_ids:r.asset_ids||[],service_lines:(r.service_lines?.length?r.service_lines:[emptyLine()]).map(x=>({...emptyLine(),...x}))})}
  function changeCustomer(v){setForm(p=>({...p,customer_id:v,location_ids:[],asset_ids:[],contracting_party_name:p.contracting_party_name||customers.find(r=>r.id===Number(v))?.name||'',contracting_party_address:p.contracting_party_address||customers.find(r=>r.id===Number(v))?.address||''}));setCustomerDetail(null)}
  function multiIds(e){return Array.from(e.target.selectedOptions).map(o=>Number(o.value))}
  function setLine(i,k,v){setForm(p=>({...p,service_lines:p.service_lines.map((r,n)=>n===i?{...r,[k]:v}:r)}))}
  function addLine(){setForm(p=>({...p,service_lines:[...p.service_lines,emptyLine()]}))}
  function removeLine(i){setForm(p=>({...p,service_lines:p.service_lines.length===1?[emptyLine()]:p.service_lines.filter((_,n)=>n!==i)}))}
  async function save(e){e.preventDefault();setError('');const body={customer_id:Number(form.customer_id),company_code:form.company_code,contracting_party_name:clean(form.contracting_party_name),contracting_party_address:clean(form.contracting_party_address),contract_number:form.contract_number.trim(),contract_type:form.contract_type.trim(),subject:clean(form.subject),start_date:form.start_date||null,end_date:form.end_date||null,term_text:clean(form.term_text),status:form.status,billing_frequency:clean(form.billing_frequency),payment_terms:clean(form.payment_terms),billing_name:clean(form.billing_name),service_confirmation:clean(form.service_confirmation),e_invoice_email:clean(form.e_invoice_email),price_adjustment_terms:clean(form.price_adjustment_terms),sla:clean(form.sla),billing_model:clean(form.billing_model),note:clean(form.note),location_ids:form.location_ids.map(Number),asset_ids:form.asset_ids.map(Number),service_lines:form.service_lines.map(row=>Object.fromEntries(Object.entries(row).filter(([k])=>!['id','sort_order'].includes(k)).map(([k,v])=>[k,clean(v)]))).filter(row=>Object.values(row).some(Boolean))};if(form.id)body.version=Number(form.version);try{const saved=await api(form.id?`/crm/contracts/${form.id}`:'/crm/contracts',{method:form.id?'PUT':'POST',body});setForm(null);setExpanded(saved.id);await load()}catch(err){setError(err.message);if(err.status===409&&form.id){try{startEdit(await api(`/crm/contracts/${form.id}`))}catch{}}}}
  return <section>
    <div className="page-head"><div><h1>Szerződések</h1><p className="muted">Az Excel nyilvántartás szerződés-, számlázási és szervizadatai; kapcsolattartói adatok nélkül. PDF szerződésarchívummal.</p></div><div className="inline-actions"><button className="secondary" onClick={()=>{const p=new URLSearchParams();if(filterCustomer)p.set('customer_id',filterCustomer);if(filterStatus)p.set('status',filterStatus);if(filterCompany)p.set('company_code',filterCompany);downloadFile(`/reports/crm-contracts.csv?${p}`)}}>CSV export</button>{canManage&&<button onClick={startNew}>Új szerződés</button>}</div></div>
    {error&&<div className="error">{error}</div>}
    <div className="panel crm-filter-row"><Field label="Keresés"><input value={q} onChange={e=>filter('q',e.target.value)} placeholder="Szerződésszám, típus, tárgy"/></Field><Field label="Vállalkozó"><select value={filterCompany} onChange={e=>filter('company',e.target.value)}><option value="">Mindhárom cég</option>{companyCodes.map(c=><option key={c}>{c}</option>)}</select></Field><Field label="Ügyfél"><select value={filterCustomer} onChange={e=>filter('customer',e.target.value)}><option value="">Minden ügyfél</option>{customers.map(r=><option value={r.id} key={r.id}>{r.name}</option>)}</select></Field><Field label="Státusz"><select value={filterStatus} onChange={e=>filter('status',e.target.value)}><option value="">Minden státusz</option>{statuses.map(r=><option key={r}>{r}</option>)}</select></Field></div>
    {form&&canManage&&<div className="panel contract-editor"><h2>{form.id?`Szerződés szerkesztése: ${form.contract_number}`:'Új szerződés'}</h2><form onSubmit={save}>
      <h3>Szerződés alapadatai</h3><div className="grid-form"><Field label="Vállalkozó"><select value={form.company_code} onChange={e=>setForm(p=>({...p,company_code:e.target.value}))}>{companyCodes.map(c=><option key={c}>{c}</option>)}</select></Field><Field label="Ügyfél"><select required value={form.customer_id} onChange={e=>changeCustomer(e.target.value)}><option value="">Válassz ügyfelet</option>{customers.map(r=><option value={r.id} key={r.id}>{r.name}</option>)}</select></Field><Field label="Szerződő cég neve"><input value={form.contracting_party_name} onChange={e=>setForm(p=>({...p,contracting_party_name:e.target.value}))}/></Field><Field label="Szerződő székhelye"><input value={form.contracting_party_address} onChange={e=>setForm(p=>({...p,contracting_party_address:e.target.value}))}/></Field><Field label="Szerződésszám"><input required maxLength="120" value={form.contract_number} onChange={e=>setForm(p=>({...p,contract_number:e.target.value}))}/></Field><Field label="Szerződés típusa"><input required maxLength="120" value={form.contract_type} onChange={e=>setForm(p=>({...p,contract_type:e.target.value}))}/></Field><Field label="Szerződés tárgya"><textarea value={form.subject} onChange={e=>setForm(p=>({...p,subject:e.target.value}))}/></Field><Field label="Státusz"><select value={form.status} onChange={e=>setForm(p=>({...p,status:e.target.value}))}>{statuses.map(r=><option key={r}>{r}</option>)}</select></Field><Field label="Kezdete / érvényesség kezdete"><input type="date" value={form.start_date} onChange={e=>setForm(p=>({...p,start_date:e.target.value}))}/></Field><Field label="Vége"><input type="date" min={form.start_date||undefined} value={form.end_date} onChange={e=>setForm(p=>({...p,end_date:e.target.value}))}/></Field><Field label="Időbeli hatály / futamidő"><input value={form.term_text} onChange={e=>setForm(p=>({...p,term_text:e.target.value}))} placeholder="pl. határozatlan (30 napos felmondás)"/></Field></div>
      <h3>Számlázás</h3><div className="grid-form"><Field label="Számlázási időszak / gyakoriság"><input value={form.billing_frequency} onChange={e=>setForm(p=>({...p,billing_frequency:e.target.value}))}/></Field><Field label="Fizetési feltétel"><input value={form.payment_terms} onChange={e=>setForm(p=>({...p,payment_terms:e.target.value}))}/></Field><Field label="Számlázási név"><input value={form.billing_name} onChange={e=>setForm(p=>({...p,billing_name:e.target.value}))}/></Field><Field label="TIG / munkalap"><input value={form.service_confirmation} onChange={e=>setForm(p=>({...p,service_confirmation:e.target.value}))}/></Field><Field label="e-számla cím"><input value={form.e_invoice_email} onChange={e=>setForm(p=>({...p,e_invoice_email:e.target.value}))}/></Field><Field label="Díjmódosítás feltétele"><textarea value={form.price_adjustment_terms} onChange={e=>setForm(p=>({...p,price_adjustment_terms:e.target.value}))}/></Field><Field label="Elszámolási modell"><input value={form.billing_model} onChange={e=>setForm(p=>({...p,billing_model:e.target.value}))}/></Field></div>
      <h3>Szerviz- és eszközsorok</h3><p className="muted">Az Excel egy szerződéshez több eszköz/szerviz sort is tartalmazhat; itt ugyanígy több sor rögzíthető.</p>{form.service_lines.map((line,i)=><div className="contract-service-line" key={i}><div className="page-head"><h4>{i+1}. szerviz/eszköz sor</h4><button type="button" className="danger small-button" onClick={()=>removeLine(i)}>Sor törlése</button></div><div className="grid-form"><Field label="Bérleti díj"><input value={line.rental_fee} onChange={e=>setLine(i,'rental_fee',e.target.value)}/></Field><Field label="Üzemeltetési díj"><input value={line.operating_fee} onChange={e=>setLine(i,'operating_fee',e.target.value)}/></Field><Field label="Klikkdíj / Bk / Col / Scan"><input value={line.click_fee} onChange={e=>setLine(i,'click_fee',e.target.value)}/></Field><Field label="Bennfoglalt mennyiség"><input value={line.included_quantity} onChange={e=>setLine(i,'included_quantity',e.target.value)}/></Field><Field label="Üzemeltető cég"><input value={line.operator_company} onChange={e=>setLine(i,'operator_company',e.target.value)}/></Field><Field label="Üzemeltetési cím / telephely"><input value={line.operator_site} onChange={e=>setLine(i,'operator_site',e.target.value)}/></Field><Field label="Karbantartási ciklus"><input value={line.maintenance_cycle} onChange={e=>setLine(i,'maintenance_cycle',e.target.value)}/></Field><Field label="Készülék csoport"><input value={line.device_group} onChange={e=>setLine(i,'device_group',e.target.value)}/></Field><Field label="Eszköz"><input value={line.device_name} onChange={e=>setLine(i,'device_name',e.target.value)}/></Field><Field label="Gyáriszám"><input value={line.serial_number} onChange={e=>setLine(i,'serial_number',e.target.value)}/></Field><Field label="Alkatrész"><textarea value={line.parts_terms} onChange={e=>setLine(i,'parts_terms',e.target.value)}/></Field><Field label="Toner"><textarea value={line.toner_terms} onChange={e=>setLine(i,'toner_terms',e.target.value)}/></Field><Field label="Kiszállás / munkadíj"><textarea value={line.travel_labor_terms} onChange={e=>setLine(i,'travel_labor_terms',e.target.value)}/></Field><Field label="Hibajavítás"><textarea value={line.repair_terms} onChange={e=>setLine(i,'repair_terms',e.target.value)}/></Field><Field label="SLA"><textarea value={line.sla} onChange={e=>setLine(i,'sla',e.target.value)}/></Field><Field label="Cseregép"><textarea value={line.replacement_device} onChange={e=>setLine(i,'replacement_device',e.target.value)}/></Field></div></div>)}<button type="button" className="secondary" onClick={addLine}>+ Szerviz/eszköz sor</button>
      <h3>Kapcsolódó rendszeradatok</h3><div className="grid-form"><Field label="Telephelyi hatály"><select multiple size="5" value={form.location_ids.map(String)} onChange={e=>setForm(p=>({...p,location_ids:multiIds(e)}))} disabled={!form.customer_id}>{selectableLocations.map(r=><option value={r.id} key={r.id}>{r.name}{r.address?` — ${r.address}`:''}{r.is_active===false?' · inaktív (meglévő)':''}</option>)}</select><small>Üresen az ügyfél összes aktív telephelye; a meglévő inaktív hivatkozások megmaradnak.</small></Field><Field label="Eszköz hatály"><select multiple size="6" value={form.asset_ids.map(String)} onChange={e=>setForm(p=>({...p,asset_ids:multiIds(e)}))} disabled={!form.customer_id}>{assets.map(r=><option value={r.id} key={r.id}>{r.internal_id} — {[r.type,r.model,r.serial_number].filter(Boolean).join(' / ')}</option>)}</select></Field><Field label="Általános SLA"><textarea value={form.sla} onChange={e=>setForm(p=>({...p,sla:e.target.value}))}/></Field><Field label="Megjegyzés"><textarea value={form.note} onChange={e=>setForm(p=>({...p,note:e.target.value}))}/></Field></div>
      <div className="form-actions"><button>Mentés</button><button type="button" className="secondary" onClick={()=>setForm(null)}>Mégse</button></div>{customerName&&<p className="muted">Kiválasztott ügyfél: {customerName}</p>}
    </form></div>}
    <div className="panel"><div className="table-wrap"><table><thead><tr><th>Vállalkozó</th><th>Szerződésszám</th><th>Ügyfél</th><th>Típus</th><th>Tárgy</th><th>Státusz</th><th>Időszak</th><th></th></tr></thead><tbody>{contracts.map(r=><React.Fragment key={r.id}><tr><td><strong>{r.company_code}</strong></td><td><strong>{r.contract_number}</strong></td><td><Link to={`/crm/customers/${r.customer_id}`}>{r.customer_name}</Link></td><td>{r.contract_type}</td><td>{r.subject||''}</td><td>{r.status}</td><td>{[fmt(r.start_date),fmt(r.end_date)].filter(Boolean).join(' – ')||r.term_text||''}</td><td><div className="inline-actions"><button className="secondary small-button" onClick={()=>setExpanded(expanded===r.id?null:r.id)}>{expanded===r.id?'Bezárás':'Részletek / archívum'}</button>{canManage&&<button className="secondary small-button" onClick={()=>startEdit(r)}>Szerkesztés</button>}</div></td></tr>{expanded===r.id&&<tr className="contract-detail-row"><td colSpan="8"><div className="contract-detail-grid"><div><strong>Szerződő:</strong> {r.contracting_party_name||r.customer_name}<br/>{r.contracting_party_address||''}<p><strong>Számlázás:</strong> {[r.billing_frequency,r.payment_terms,r.billing_name].filter(Boolean).join(' · ')}</p><p><strong>Díjmódosítás:</strong> {r.price_adjustment_terms||''}</p></div><div><strong>Hatály:</strong> {r.location_ids.length?`${r.location_ids.length} telephely`:'összes telephely'} · {r.asset_ids.length?`${r.asset_ids.length} eszköz`:'nincs eszközkorlát'}<p><strong>Szerviz/eszköz sorok:</strong> {r.service_lines?.length||0}</p></div></div><ContractArchiveTable contract={r} user={user} canManage={canManage} onChanged={load}/></td></tr>}</React.Fragment>)}{!contracts.length&&!loading&&<tr><td colSpan="8" className="muted">Nincs a szűrésnek megfelelő szerződés.</td></tr>}</tbody></table></div>{loading&&<p>Betöltés...</p>}</div>
  </section>
}
